Repository ucsb-cs156-f23/proj-courses-f23-7pm-4, pull requests merged in 2023-12, with the labels that each got.

#44 EricM5 - Add Github info to /api/SystemInfo endpoint and display on Developer Page
  pom.xml
  src/main/java/edu/ucsb/cs156/courses/CoursesApplication.java
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/SystemInfoServiceImpl.java
Labels: 10, Merge Candidate

#73 BC - Deployed dokku and updated README
  README.md
Labels: Merge Candidate, 5

#74 Azhu - Add New Section Number Column
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 5
