Repository ucsb-cs156-f23/proj-courses-f23-7pm-4, pull requests merged in 2023-11, with the labels that each got.

#28 azhou - Course Details Placeholder Page
  frontend/src/App.js
  frontend/src/main/pages/CourseDetails/CourseDetailsPage.js
  frontend/src/stories/pages/HomePage/CourseDetails/CourseDetailsPage.stories.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsPage.test.js
Labels: 10

#26 azhou - Personal Schedule Default Quarter Fix
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
Labels: 10, Merge Candidate

#31 EricM5 - Fix Bug 'Search by Instructor's '+' button in table does nothing'
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/SectionsTableBase.js
  frontend/src/main/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.js
  frontend/src/tests/components/SectionsTableBase.test.js
  frontend/src/tests/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.test.js
Labels: 10, Merge Candidate

#42 EricM5 - Display SystemInfo on Developer Page
  frontend/src/main/pages/DeveloperPage.js
  frontend/src/stories/pages/DeveloperPage.stories.js
Labels: 10, Merge Candidate

#49 azhou - Fixed typo in footer
  frontend/src/main/components/Nav/Footer.js
Labels: Merge Candidate, 5

#45 Added section status to table
  frontend/src/fixtures/sectionFixtures.js
  frontend/src/fixtures/sectionOverTimeFixtures.js
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10, Merge Candidate

#56 BC - Make finals information available, Part 1
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/documents/FinalsFixtures.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate

#58 BC - Added fields for CourseDetails
  frontend/src/main/components/Courses/CourseDetailsTable.js
  frontend/src/tests/components/Courses/CourseDetailsTable.test.js
Labels: Merge Candidate, 5

#46 azhou - Course Details Button
  frontend/src/App.js
  frontend/src/main/components/Courses/CourseDetailsTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/pages/CourseDetails/CourseDetailsPage.js
  frontend/src/main/utils/quarterUtilities.js
  frontend/src/tests/components/Courses/CourseDetailsTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsPage.test.js
  frontend/src/tests/utils/quarterUtilities.test.js
Labels: 10, Merge Candidate

#71 azhou - SectionsOverTimeTable More-info Button
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
Labels: 10
